### Foundations & Control Flow

Features of Python
1. Object Oriented Programming - we can implement oop concepts like Polymorphism, Inheritance, Encapsulation, Abstraction.
2. Dynamically type language - we don't need to declare the data type of a variable explicitly.
3. Interpreted Language - executes line by line
4. Multi-Paridigm - supports multiple programming styles:
    object oriented programming = organize code and classes
    functional programming = organize the program as sequence of functions [Apply functions to data]
    imperative programming = variables, literals, algorithm to tell how it is to done
5. Extensible - can interact with multiple programming languages such as C/C++
6. Embeded - Python can be embedded inside applications written in other languages such as C++


Write a function to check if a string is a palindrome without using built-in string reversal methods like [::-1] or reversed()

In [24]:
# Logic left read and right read should be same
def is_palindrome(s):
    # Normalized string
    normalized_str = ''.join(char.lower() for char in s if char.isalnum()) # already ignoring spaces and punctuations
    left = 0
    right = len(normalized_str) - 1
    
    while left < right:
        if normalized_str[left] != normalized_str[right]:
            return False
        left += 1
        right -= 1
    return True 

# print(is_palindrome("A man, a plan, a canal: Panama")) 
# print("Aman".isalnum()) # True
# print("Aman".isalpha()) # True
print("½".isnumeric()) # True
# print("123.07".isdecimal()) # False isnumeric() and isdecimal() are different. isdecimal() returns True only for decimal characters, while isnumeric() returns True for numeric characters, including fractions and subscripts.
# print("123".isdigit()) # True

True


### Functional Programming & Memory-Efficient Iteration

Iterator vs Generator
Iterator is an object that knows how to give you the next value.

Generator is a special type of iterator created using a function containing the yield keyword. Generator is more memory efficient.

In [25]:
# Iterator example
numbers = [10, 20, 30]
iter_obj = iter(numbers) # numbers.__iter__()

print(next(iter_obj))  # 10 # iter_obj.__next__()
print(next(iter_obj))  # 20
print(next(iter_obj))  # 30
# print(next(iter_obj))  # StopIteration exception

10
20
30


In [26]:
# Generator example
def my_generator():
    yield 1
    yield 2
    yield 3

        
my_gen = my_generator()
print(next(my_gen))  # 1
print(next(my_gen))  # 2
print(next(my_gen))  # 3
# print(next(my_gen))  # StopIteration exception

1
2
3


Implement a custom generator that streams a massive file line-by-line and yields only lines containing a specific keyword. 

The Concept: Traditional file parsing (.readlines()) forces the entire file into RAM, crashing systems on huge files. Generators use lazy evaluation, reading and yielding one line at a time while keeping memory footprint constant near 0 MB.

In [27]:
def filter_log_stream(file_path: str, keyword: str):
    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            if keyword in line:
                yield line.strip()

In [28]:
gen = filter_log_stream("huge_sample_logs.txt", "ERROR")
# print(len(list(gen)))  # prints total number of lines containing "ERROR". You cannot use the generator again after this because it has been exhausted.

for i in range(5):
    print(next(gen))  # prints first 5 lines containing "ERROR"

2026-09-12 22:03:03 [ERROR] request_id=req-00000003 service=data-pipeline message=Payment transaction processed
2026-09-12 22:07:07 [ERROR] request_id=req-00000007 service=data-pipeline message=API request completed successfully
2026-09-12 22:10:10 [ERROR] request_id=req-00000010 service=data-pipeline message=Connection timeout while contacting service
2026-09-12 22:13:13 [ERROR] request_id=req-00000013 service=data-pipeline message=File processing completed
2026-09-12 22:17:17 [ERROR] request_id=req-00000017 service=data-pipeline message=Background job started


In [29]:
# Traditional way of reading a file line by line
def process_error(file_path: str, keyword: str):
    lines = []
    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            if keyword in line:
                lines.append(line.strip())
    return lines

In [30]:
obj = process_error("huge_sample_logs.txt", "ERROR")
print(len(obj))  # prints total number of lines containing "ERROR". You cannot use the generator again after this because it has been exhausted.

648976


Lamda function<br>
is a small, anonymous function that you can define in a single line

lambda arguments: [expression, conditional expresions]

In [31]:
multiply = lambda a, b, c: a * b * c

print(multiply(2, 3, 4))

24


### Decorators
A decorator is a function that takes another function, adds/modifies behavior, and returns a function.

In [ ]:
# We are defining our own decorator function called my_decorator. It takes a function func as an argument and returns a new function wrapper that adds some additional behavior before and after calling func.
# A decorator always returns a wrapper function that wraps the original function.
def my_decorator(func):
    def wrapper():
        print("Before function")

        # func()

        print("After function")

    return wrapper

In [37]:
def greet():
    print("Hello")


greet_obj = my_decorator(greet)

greet_obj()

Before function
After function


In [ ]:
# Alternatively, we can use the @my_decorator syntax to apply the decorator to the greet function. This is a more concise way of applying decorators in Python.
@my_decorator
def greet():
    print("Hello")
   
# Whenever we call greet(), it will only execute the wrapper function defined in the my_decorator, which prints "Before function", then calls the original greet function, and finally prints "After function". 
greet()

Before function
After function


Write a custom decorator @retry(times=3) that re-runs a function if it encounters a runtime exception.

In [1]:
# Defining a decorator that takes arguments
def retry(times=3):
    def decorator(func):
        def wrapper():
            for i in range(times):
                try:
                    return func()
                except Exception as e:
                    print(f"Attempt {i + 1} failed: {e}")
        return wrapper
    return decorator

In [12]:
import random

@retry(times=3)
def fetch_unstable_api_data():
    value = random.random()
    print("value=", value)
    if value > 0.3: # simulating an unstable network connection probability
        raise ConnectionError("Network dropped!")
    return "Success Data"

try:
    print(fetch_unstable_api_data())
except ConnectionError as e:
    print(f"All attempts failed: {e}")

value= 0.4630456057634911
Attempt 1 failed: Network dropped!
value= 0.931196529368061
Attempt 2 failed: Network dropped!
value= 0.285660153371893
Success Data


A closure is a property of a function that allows it to retain access to variables (state) from its enclosing lexical scope, even after that scope has finished executing

### NumPy and Pandas

#### The NumPy Foundation (Array Mechanics & Speed)

Q1: Why are NumPy operations significantly faster than standard Python loops for numerical data processing?

Python lists are arrays of pointers to scattered objects, requiring type-checking and reference resolution for every element. 

NumPy arrays (ndarrays) store data in contiguous blocks of memory with a single uniform data type (homogenous).


In [ ]:
import numpy as np
import time

# Traditional Python Loop
py_list = list(range(100_000_000)) # 100M records
start = time.time()
py_list_squared = [x ** 2 for x in py_list]
print(f"Python List Time: {time.time() - start:.4f} seconds")

Python List Time: 6.4015 seconds


In [17]:
# Vectorised NumPy Array
np_array = np.arange(100_000_000) # 100M records
start = time.time()
np_array_squared = np_array ** 2  # Vectorised operation
print(f"NumPy Array Time: {time.time() - start:.4f} seconds")

NumPy Array Time: 0.3024 seconds


Q2: What is Broadcasting in NumPy?

Broadcasting is NumPy's mechanism for performing an arithmetic operation between arrays that have different shapes.
The smaller array is effectively "broadcast" across the larger array so that they have compatible shapes.

In [35]:
# Let's have a 2D matrix of 3x3 (3,3)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Let's have a 1D matrix of 1x3 (3,)
row_vector = np.array([10, 20, 30])

broadcasted_result_1 = matrix + row_vector  # Broadcasting operation: +,-,*,/,%, **
print(broadcasted_result_1)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [36]:
# Let's have a 2D matrix of 3x1 (3,1)
column_vector = np.array([[10],[20],[30]])

broadcasted_result_2 = matrix + column_vector  # Broadcasting operation: +,-,*,/,%, **
print(broadcasted_result_2)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


Broadcasting Rules:

The Two dimensions are compatible only if (reading from right to left):
1. They are equal <br>
Eg: 3x3 and 3x3, 2x2 and 2x2, etc.

2. One of them is 1 <br>
Eg: 3x3 and 1x3 (right: 3 and 3 -> equal, left: 3 and 1 -> one of them is 1) <br>
    3x3 and 3x1 (right: 3 and 1 -> one of them is 1, left: 3 and 3 -> equal)

In [40]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

incompatible_vector_1 = np.array([10, 20])  # 1D matrix of 1x2 (2,)
incompatible_vector_2 = np.array([[10], [30]])  # 2D matrix of 2x1 (2,1)

In [43]:
try:
    broadcasted_result_3 = matrix + incompatible_vector_1
    print(broadcasted_result_3)
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (3,3) (2,) 


In [44]:
try:
    broadcasted_result_4 = matrix + incompatible_vector_2
    print(broadcasted_result_4)
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (3,3) (2,1) 


In [45]:
# Let's have 3D matrix of 2x3x3 (2,3,3)
matrix_3d = np.array([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]
                       ])

row_vector_3d = np.array([100, 200, 300])  # 1D matrix of 1x3 (3,)
broadcasted_result_5 = matrix_3d + row_vector_3d  # Broadcasting
print(broadcasted_result_5)

[[[101 202 303]
  [104 205 306]
  [107 208 309]]

 [[110 211 312]
  [113 214 315]
  [116 217 318]]]


#### Pandas Performance & Memory Optimisation

Data types in Pandas:

1. Numeric:<br>
(int8 -> 1 Byte, int16 -> 2 Bytes, int32 -> 4 Bytes, int64 -> 8 Bytes)

2. Boolean

3. Object <br>
It is a generic container for Python objects; strings are a common use case

4. Datetime

5. Timedelta

6. Category <br>:
It's useful when a column has relatively few unique values repeated many times.


Q3: How do you optimise a massive Pandas DataFrame that is running out of memory?

The Concept: By default, Pandas reads integer columns as int64 and float columns as float64. Text data is cast as a generic object type. If a column has small integers or repetitive text, it wastes immense amounts of RAM.

The Solution Strategy:Downcast numeric columns (e.g., int64 to int8 or int32).Convert low-cardinality text columns (like "Gender", "Country", or "Status") into the category data type.

In [55]:
import pandas as pd

# Mock DataFrame representing a heavy transactions log
data = {
    'transaction_id': range(10000), # 10000 unique transaction IDs
    'status': ['Success', 'Pending', 'Failed', 'Success'] * 2500, # Highly repetitive text
    'age': [25, 30, 45, 60] * 2500
}
df_1 = pd.DataFrame(data)
df_2 = pd.DataFrame(data)

print("Initial Memory:")
print(df_1.memory_usage(deep=True), "(Bytes)") # returns memory usage of each column in bytes, including the index. The deep=True parameter ensures that the memory usage of object types (like strings) is calculated accurately.

print("\nInitial Memory:")
print(df_1.memory_usage(deep=True)/1024, "(KB)") # returns memory usage of each column in bytes


Initial Memory:
Index                132
transaction_id     80000
status            147500
age                80000
dtype: int64 (Bytes)

Initial Memory:
Index               0.128906
transaction_id     78.125000
status            144.042969
age                78.125000
dtype: float64 (KB)


In [56]:
# Optimisation steps
df_2['transaction_id'] = df_2['transaction_id'].astype('int16')  # int64 to int16
df_2['status'] = df_2['status'].astype('category')  # Shrinks memory for text strings
df_2['age'] = pd.to_numeric(df_2['age'], downcast='unsigned') # int64 to uint8

print("\nOptimised Memory:")
print(df_2.memory_usage(deep=True), "(Bytes)")
print("\nOptimised Memory:")
print(df_2.memory_usage(deep=True)/1024, "(KB)")


Optimised Memory:
Index               132
transaction_id    20000
status            10045
age               10000
dtype: int64 (Bytes)

Optimised Memory:
Index              0.128906
transaction_id    19.531250
status             9.809570
age                9.765625
dtype: float64 (KB)


Q4: Given a DataFrame containing retail transactional details, how do you find the top 2 highest-spending customers in each region?

The Concept: This evaluates your ability to use window-like analytics functions in Pandas via .groupby(), .sum(), and .rank() or .nlargest().